var foo;

try	{
	foo.length;
}
catch (err){
	console.log(err);
}

console.log(err);